In [7]:
import numpy as np

y = np.array([1,2,3,4,5])
y[1::2]
y[:-1]

array([1, 2, 3, 4])

In [26]:
np.mgrid[-1:1:100j, -2:2:100j]

array([[[-1.        , -1.        , -1.        , ..., -1.        ,
         -1.        , -1.        ],
        [-0.97979798, -0.97979798, -0.97979798, ..., -0.97979798,
         -0.97979798, -0.97979798],
        [-0.95959596, -0.95959596, -0.95959596, ..., -0.95959596,
         -0.95959596, -0.95959596],
        ..., 
        [ 0.95959596,  0.95959596,  0.95959596, ...,  0.95959596,
          0.95959596,  0.95959596],
        [ 0.97979798,  0.97979798,  0.97979798, ...,  0.97979798,
          0.97979798,  0.97979798],
        [ 1.        ,  1.        ,  1.        , ...,  1.        ,
          1.        ,  1.        ]],

       [[-2.        , -1.95959596, -1.91919192, ...,  1.91919192,
          1.95959596,  2.        ],
        [-2.        , -1.95959596, -1.91919192, ...,  1.91919192,
          1.95959596,  2.        ],
        [-2.        , -1.95959596, -1.91919192, ...,  1.91919192,
          1.95959596,  2.        ],
        ..., 
        [-2.        , -1.95959596, -1.91919192, ...,

In [29]:
#x = np.arange(1,10,.5)
print(x)
x[-1:3:-1]

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.
  8.5  9.   9.5]


array([ 9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,  4.5,
        4. ,  3.5,  3. ])

In [32]:
x,y = np.ogrid[5:3:-1,0:3]
x

array([[5],
       [4]])

In [53]:
a= np.linspace(1,9,9)
a.shape = (3,3)
b=a.flat
b[:]

print(a[a >5])
np.choose(a>5,(a,5))

(a,5)

[ 6.  7.  8.  9.]


(array([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]]), 5)

In [66]:
a = np.ones((3, 5))
#print(a)
b = np.ones((5,))
b.reshape(1, 5)
#print(b)
print(a[np.newaxis, :])
a+b

[[[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]]


array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [77]:
from math import sqrt
import matplotlib.pyplot as plt
a = np.linspace(0, 1, 15) - 0.5
b = a[:, np.newaxis] # b.shape == (15, 1)
dist2 = a**2 + b**2 # broadcasting sum.
plt.imshow(dist2)
plt.colorbar()
